### ISSUE TITLE
Insert not detected?

### ISSUE THREAD

**Issue by gerthelsen** [KengoTODA/java-diff-utils#5]
dcl 1 four_copy,
        5 a  char(1),
        5 b  char(1);

  dcl 1 four_copy,
        5 a  char(1),
        5 b  char(1),
        5 X  char(1),
        5 Y  char(1),
        5 c  char(1);

List<DiffRow> diffs = generator.generateDiffRows(baselineSource, revisedSource);

=> X, Y and c are all classified as "changed", not "inserted"

**Comment by KengoTODA** [comment]
Sorry but this repository it not maintained. Please fork and manage by own.
